name: Texture/Model Contribution
description: Create a texture/model contribution issue, so we can work on adding the texture/model to the mod.
body:
  - type: markdown
    attributes:
      value: "Thank you for submitting a texture/model contribution! 
      Please fill out the following information for the issue, that will help with the Pull Request later on."
  - type: input
    id: texture
    attributes:
      label: "Texture/Model"
      description: "Which texture/model did you create/edit?"
      placeholder: "Example: Iron Sword Texture/Model"
    validations:
      required: true
  - type: dropdown
    id: scope
    attributes:
      label: "Scope"
      description: "Is the texture for something that is missing a texture, or meant to overwrite an existing one?"
      options:
        - "Missing Texture"
        - "Overwrite Existing Texture"
    validations:
        required: true
  - type: textarea
    id: other
    attributes:
      label: "Additional Information"
      description: "Please provide any additional information you think is necessary."
      placeholder: "Example: I created a new texture for the Iron Sword, but I am not sure if it fits the mod's style."