name: Translation Contribution
description: Create a translation contribution issue, so we can work on adding the translation to the mod.
body:
  - type: markdown
    attributes:
      value: "Thank you for submitting a translation contribution! 
      Please fill out the following information for the issue, that will help with the Pull Request later on."
  - type: input
    id: language
    attributes:
      label: "Language"
      description: "Which language did you do translations for?"
      placeholder: "Example: French"
    validations:
        required: true
  - type: dropdown
    id: scope
    description: "Did you add to an existing translation or did you create a new one?"
    attributes:
        label: "Scope"
        options:
            - "Existing Translation"
            - "New Translation"
    validations:
        required: true
  - type: textarea
    id: other
    description: "Please provide any additional information you think is necessary."
    attributes:
        label: "Additional Information"
        placeholder: "Example: I translated the mod to French, but I am not a native speaker."